# Here there will be the description of the Model

### The one below is the Excel containing the information regarding the various parameters

## ALL THIS INFORMATION SHOULD BE UNPACKED AND PRESENTED HERE IN A BETTER FORM

In [1]:
import pandas as pd

In [18]:
xls = pd.ExcelFile('Data_Dictionary.xlsx')

df1 = pd.read_excel(xls, 'Travel Data')
df1.drop(0, inplace=True)
df1.rename(columns = {'Data Dictionary - Travel Data': 'Column Name','Unnamed: 1': 'Column Description', 'Unnamed: 2': 'Column Value Examples'}, inplace = True)

df2 = pd.read_excel(xls, 'Survey Data')
df2.drop(0, inplace=True)
df2.rename(columns = {'Data Dictionary - Survey Data': 'Column Name','Unnamed: 1': 'Column Description', 'Unnamed: 2': 'Column Value Examples'}, inplace = True)

In [19]:
df1

,Column Name,Column Description,Column Value Examples
1,ID,The unique ID of the passenger,"Continuous values like 98800001, 98800002, etc."
2,Gender,The gender of the passenger,Male\nFemale
3,Customer_Type,Loyalty type of the passenger,Loyal Customer\nDisloyal Customer
4,Age,The age of the passenger,"Continuous values like 48, 52, 9, etc."
5,Type_Travel,Purpose of travel for the passenger,Personal Travel\nBusiness Travel
6,Travel_Class,The train class that the passenger traveled in,Business\nEco
7,Travel_Distance,The distance traveled by the passenger,"Continuous values like 272, 780, 853, etc."
8,Departure_Delay_in_Mins,The delay (in minutes) in train departure,"Continuous values like 9, 15, 13, etc."
9,Arrival_Delay_in_Mins,The delay (in minutes) in train arrival,"Continuous values like 0, 15, 18, etc."

In [20]:
df2

,Column Name,Column Description,Column Value Examples
1,ID,The unique ID of the passenger,"Continuous values like 98800001, 98800002, etc."
2,Platform_Location,How convenient the location of the platform is...,Very Inconvenient\nInconvenient\nNeeds Improve...
3,Seat_Class,The type of the seat class in the train \nGree...,Ordinary\nGreen Car
4,Overall_Experience,The overall experience of the passenger,1 - Satisfied\n0 - Not Satisfied
5,Seat_Comfort,The comfort level of the seat for the passenger,Extremely Poor\nPoor\nNeeds Improvement\nAccep...
6,Arrival_Time_Convenient,How convenient the arrival time of the train i...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
7,Catering,How convenient the catering service is for the...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
8,Onboard_Wifi_Service,The quality of the onboard Wi-Fi service for t...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
9,Onboard_Entertainment,The quality of the onboard entertainment for t...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
10,Online_Support,The quality of the online support for the pass...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
11,Ease_of_Online_Booking,The ease of online booking for the passenger,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
12,Onboard_Service,The quality of the onboard service for the pas...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
13,Legroom,Legroom is the general term used in place of t...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
14,Baggage_Handling,The convenience of baggage handling for the pa...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
15,CheckIn_Service,The convenience of the check-in service for th...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
16,Cleanliness,The passenger's view of the cleanliness of the...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
17,Online_Boarding,The convenience of the online boarding process...,Extremely Poor\n Poor\nNeeds Improvement\nAcce...
18,NaN,NaN,NaN
19,Notes:,NaN,NaN
20,1. The categories of the ordinal variables in ...,NaN,NaN